filter:
    excluded_paths:
        - 'vendor/*'
        - 'tests/*'
        - 'examples/*'
    paths: {  }
tools:
    php_analyzer:
        enabled: true
        extensions:
            - php
        dependency_paths: {  }
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'tests/*'
                - 'examples/*'
            paths: {  }
        path_configs: {  }
    php_sim:
        enabled: true
        min_mass: 16
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'tests/*'
                - 'examples/*'
            paths: {  }
    php_pdepend:
        enabled: true
        configuration_file: null
        suffixes:
            - php
        excluded_dirs: {  }
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'tests/*'
                - 'examples/*'
            paths: {  }
    php:
        code_rating: true
        duplication: true
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'tests/*'
                - 'examples/*'
            paths: {  }
